name: Deployment Workflow

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
    

jobs:

  # Run unit tests to make sure everything is 👍
  tests:

    runs-on: ubuntu-latest

    steps:
    
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      name: 'Setup PHP 8.0'
      with:
        php-version: '8.0'
    
    - uses: actions/checkout@v2
      name: 'Checkout repository'

    - name: 'Copy .env'
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    
    - name: 'Install Dependencies'
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    
    - name: 'Generate key'
      run: php artisan key:generate
    
    - name: 'Update Directory Permissions'
      run: chmod -R 777 storage bootstrap/cache
    
    - name: 'Run Tests'
      run: php artisan test
